format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$kubernetes\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are confguring is "character"
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
truncate_to_repo = false
format = "in [$path]($style)[$read_only]($read_only_style) "

[git_branch]
truncation_length = 24

[hg_branch]
truncation_length = 24

[time]
disabled = false
format = "[$time]($style) "
utc_time_offset = "+5.5"
style = "bold #8fbcbb"

[hostname]
ssh_only = false
trim_at = "."
disabled = false
format =  "on [$hostname]($style) "
style = "bold dimmed #8fbcbb"

[username]
show_always = true
style_user = "bold #8fbcbb"
style_root = "bold #bf616a"
format = "[$user]($style) "

[aws]
format = '[ ($profile) ($region )]($style)'
[aws.region_aliases]
ap-south-1 = "mum"

[gcloud]
format = '[ ($active) ($region)]($style) '
[gcloud.region_aliases]
asia-south1 = "mum"

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
[kubernetes.context_aliases]
"arn:aws:eks:ap-south-1:844975015264:cluster/test" = "test-cluster"
"gke_maha-mela_asia-south1_mela-cluster" = "mela-cluster"
"vidur.butalia@mahamela.in@infra.ap-south-1.eksctl.io" = "infra-cluster"
[shlvl]
disabled = false
format = "[ $shlvl]($style) "
