# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are confguring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"

[directory]
truncate_to_repo = false

[git_branch]
truncation_length = 24

[hg_branch]
truncation_length = 24

[time]
disabled = false
format = "[$time]($style) "
utc_time_offset = "+5.5"
style = "bold #8fbcbb"

[hostname]
ssh_only = false
trim_at = "."
disabled = false
style = "bold dimmed #8fbcbb"

[username]
show_always = true
style_user = "bold #8fbcbb"
style_root = "bold #bf616a"
